version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_network
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka_network
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  weather-producer:
    image: weather-producer:latest
    container_name: weather-producer
    build:
      context: .
      dockerfile: ./weatherproducer/Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka_network

  strain-producer:
    image: strain-producer:latest
    container_name: strain-producer
    build:
      context: .
      dockerfile: ./strainproducer/Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka_network
